### ISSUE TITLE
Low end pc

### ISSUE THREAD

**Issue by OG-Prince-X** [Engine-Simulator/engine-sim-community-edition#16]
Please make a setting to reduce graphics or anything that makes it hard to produce clean sounding and low latency. i really just wanna hear the sound so badly

**Comment by Abdullah-Ajeebi** [comment]
Try modding the source code for the older repo to make it multi-thread
compatible. Alternatively you can go to the internet and find solutions to
make it multi-thread. Or if are you really stuck in a hole try using a
lower exhaust manifold system engine.

في الأحد، ١٩ مارس ٢٠٢٣, ٤:٣٧ م OG-Prince-X ***@***.***> كتب:

**Comment by raspitakesovertheworld** [comment]
Get a new PC or a used one that is newer than yours, chances is that yours is ancient. Today you get older PCs for free and very fancy powerful CPUs can be had for almost nothing. Sometimes you will get a more powerful and luxurious machine than a new one if you buy used, that is even true for cars.

**Comment by ange-yaghi** [comment]
Reading the tutorial should help with this: https://github.com/Engine-Simulator/engine-sim-community-edition/blob/master/tutorial/01_getting_started/01_getting_started.md
