### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by 2twenty-three3** [Engine-Simulator/engine-sim-community-edition#2]
can't run anything since it just wants you to download like 6000 different things which is really sketchy ngl. There's also no support or tutorial on how to run it. Would be really nice if you could run it but no, to good to be true.

**Comment by Abdullah-Ajeebi** [comment]
https://github.com/Engine-Simulator/engine-sim-community-edition#installation-instructions

**Comment by ange-yaghi** [comment]
Before creating a ticket, please at least read the README as Abdullah-Ajeebi linked to you above. There both installation instructions and a tutorial and there is absolutely nothing you need to download to run this application. Thank you.
