### ISSUE TITLE
Black screen when i start the game

### ISSUE THREAD

**Issue by Lechatdu17** [Engine-Simulator/engine-sim-community-edition#28]
Hi, so my case is pretty particular i’m not on windows, i’m on Mac OS, i’m using a application named CrossOver. Anyway, i already played Engine simulator with crossover but now, when i start the game, there a gray screen for like 0,5 seconds and after there’s a black screen, but i can still start the engine and hear it. Thanks if somebody can help me. By the way sorry if my english is not perfect i’m french.

**Comment by AngusCrump** [comment]
I don't know how to fix this problem on crossover, but it is built from wineskin, and a was able to run it in that. In an app made bye wineskin, run the Wineskin.app and hit Winetricks.
![Screenshot 2023-06-27 at 5 40 39 pm](https://github.com/Engine-Simulator/engine-sim-community-edition/assets/121205522/b3d5b29f-bff9-4e35-a27f-3d20924598ec)
Once Winetricks has opened, search for dxvk_master in the search bar. Select the dxvk_master in the dlls section. Hit run and wait for Winetricks to do it's magic. 

Now download the latest engine simulator zip file, unzip it, and move the folder to somewhere in the the drive_c alias. 
Run the Wineskin app again, this time selecting advanced and hitting browse on the Windows app field. Navigate to the engine sim folder you moved there earlier and select the exe file in the bin folder. You should now be able to run the app and enjoy the simulator!

**Comment by Lechatdu17** [comment]
> I don't know how to fix this problem on crossover, but it is built from wineskin, and a was able to run it in that. In an app made bye wineskin, run the Wineskin.app and hit Winetricks. ![Screenshot 2023-06-27 at 5 40 39 pm](https://user-images.githubusercontent.com/121205522/249073449-b3d5b29f-bff9-4e35-a27f-3d20924598ec.png) Once Winetricks has opened, search for dxvk_master in the search bar. Select the dxvk_master in the dlls section. Hit run and wait for Winetricks to do it's magic.
> 
> Now download the latest engine simulator zip file, unzip it, and move the folder to somewhere in the the drive_c alias. Run the Wineskin app again, this time selecting advanced and hitting browse on the Windows app field. Navigate to the engine sim folder you moved there earlier and select the exe file in the bin folder. You should now be able to run the app and enjoy the simulator!

It work really well for me, Thanks !

**Comment by vmqxdv** [comment]
> I don't know how to fix this problem on crossover, but it is built from wineskin, and a was able to run it in that. In an app made bye wineskin, run the Wineskin.app and hit Winetricks. ![Screenshot 2023-06-27 at 5 40 39 pm](https://private-user-images.githubusercontent.com/121205522/249073449-b3d5b29f-bff9-4e35-a27f-3d20924598ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjcyODgsIm5iZiI6MTcxNzE2Njk4OCwicGF0aCI6Ii8xMjEyMDU1MjIvMjQ5MDczNDQ5LWIzZDViMjlmLWJmZjktNGUzNS1hMjdmLTNkMjA5MjQ1OThlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxNDQ5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzVkZGMxMTE5Y2RkOGIxYTJiZDM0NzA5OWMwNmNmYWU5YTc0OTA5ZTJiNTY4NDZhMjljM2I5MGE5YzRjMTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tXSzy8mE707R6yh3ZXdbqcnPMAYiPcT6TOA3CYqNy6s) Once Winetricks has opened, search for dxvk_master in the search bar. Select the dxvk_master in the dlls section. Hit run and wait for Winetricks to do it's magic.
> 
> Now download the latest engine simulator zip file, unzip it, and move the folder to somewhere in the the drive_c alias. Run the Wineskin app again, this time selecting advanced and hitting browse on the Windows app field. Navigate to the engine sim folder you moved there earlier and select the exe file in the bin folder. You should now be able to run the app and enjoy the simulator!

I can't find anywhere this "dxvk_master", where can I download it?
