### ISSUE TITLE
Audio frames are skipped constantly.

### ISSUE THREAD

**Issue by beqabeqa473** [Engine-Simulator/engine-sim-community-edition#35]
Hello.

May be you could give me an advice.

Intel core i7 10700, 32 GB ram, m2 Samsung 970 evo plus, Nvidia rtx3060, Windows 10 with latest updates.
When trying to start an engine audio frames are beeing constantly skipped and crackling sound is beeing heared.
I tried to press N key and tune with scroll wheel but without any effect.

What i can do to improver situation?

Thanks.

**Comment by Cineka** [comment]
I have the same issue when using any engine that is not included with the install, I haven't found a fix yet, any luck?

**Comment by Abdullah-Ajeebi** [comment]
Try using N+Scroll (Scroll down to lower the simulation frequency, scroll up to increase the simulation frequency)

**Comment by beqabeqa473** [comment]
Restart of pc fixed my problem
