### ISSUE TITLE
can't change standart engine

### ISSUE THREAD

**Issue by SomeCoolName54564654** [Engine-Simulator/engine-sim-community-edition#4]
i downloaded the newest v0.1.12.0A, and some community rotary engine, put in folder, changed main mr file, launched sim and engine don't change to it

**Comment by ange-yaghi** [comment]
Hello, 0.1.12 does not use `main.mr` by default. Please read the [Getting Started Tutorial](https://github.com/Engine-Simulator/engine-sim-community-edition/blob/master/tutorial/01_getting_started/01_getting_started.md) where the changing engines section is near the bottom.
