### ISSUE TITLE
Error code: 13

### ISSUE THREAD

**Issue by Kilgarragh** [Engine-Simulator/engine-sim-community-edition#44]
error code 13 when running under 64bit wine 8.0(bottles)

**Comment by EmulatedGoodness2** [comment]
This fixed yet?

**Comment by Kilgarragh** [comment]
> This fixed yet?

No, a newer version has not been released since i opened this. Considering that all work is currently being put to the new, 3d engine simulator: i doubt this will ever be fixed.
